// Generates src/data/usMap.js — lower-48 outline, state borders and sample points,
// pre-projected into a 1000x620 space. Run once: `node scripts/build-us-map.mjs`
// (requires dev deps: us-atlas topojson-client topojson-simplify d3-geo)
import fs from 'node:fs';
import { createRequire } from 'node:module';
const require = createRequire(import.meta.url);
const topo = require('us-atlas/states-10m.json');
import * as tc from 'topojson-client';
import * as ts from 'topojson-simplify';
import { geoAlbers, geoPath, geoContains } from 'd3-geo';

const EXCLUDE = new Set(['02', '15', '60', '66', '69', '72', '78']); // AK, HI, territories
const pre = ts.presimplify(topo);
const simp = ts.simplify(pre, ts.quantile(pre, 0.12));
const geoms = simp.objects.states.geometries.filter(g => !EXCLUDE.has(g.id));
const obj = { type: 'GeometryCollection', geometries: geoms };
const nation = tc.merge(simp, geoms);
const borders = tc.mesh(simp, obj, (a, b) => a !== b);

const W = 1000, H = 620;
const proj = geoAlbers().fitExtent([[20, 20], [W - 20, H - 20]], nation);
const round = s => s.replace(/(\d+\.\d{1})\d+/g, '$1');
const path = geoPath(proj);
const outline = round(path(nation));
const inner = round(path(borders));

// deterministic pseudo-random points inside the lower 48 (illustrative network)
let seed = 7;
const rnd = () => ((seed = (seed * 16807) % 2147483647) / 2147483647);
const pts = [];
while (pts.length < 320) {
  const x = 20 + rnd() * (W - 40), y = 20 + rnd() * (H - 40);
  const ll = proj.invert([x, y]);
  if (ll && geoContains(nation, ll)) pts.push([Math.round(x), Math.round(y)]);
}
const out = `// Generated by scripts/build-us-map.mjs from us-atlas (Census cartographic boundaries).
// Contiguous United States only (no Alaska/Hawaii/territories), Albers projection, 1000x620.
export const US_W = ${W};
export const US_H = ${H};
export const US_OUTLINE = ${JSON.stringify(outline)};
export const US_BORDERS = ${JSON.stringify(inner)};
export const US_POINTS = ${JSON.stringify(pts)};
`;
fs.mkdirSync(new URL('../src/data/', import.meta.url), { recursive: true });
fs.writeFileSync(new URL('../src/data/usMap.js', import.meta.url), out);
console.log('bytes', out.length, 'outline', outline.length, 'borders', inner.length);
